### PR TITLE
remove mirah gem dependency

### PR DESCRIPTION
**Pull request by uujava**
- no mirah project dependency
- mirahc (0.1.4) jar downloaded if absent

### CODE REVIEW

**Comment by uujava** [comment]
added minor fix for mmeta based parsers be able to decompile to java more cleanly

**Comment by baroquebobcat** [comment]
Looks good to me! Do you have access to merge here, or do you need me to?

**Comment by uujava** [comment]
seems do not have an access for this repo, please merge

**Comment by baroquebobcat** [comment]
Will do!

**Pull request merged**
